Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.TableReadCap}
            WriteCapacityUnits: ${self:custom.TableWriteCap}
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.TableReadCap}
        WriteCapacityUnits: ${self:custom.TableWriteCap}
      TableName: ${self:custom.tableNames.orders}
